// mwiii decomp prototype
#using scripts\unittest\util.gsc;

#namespace namespace_eb31a7ea746bf7d0;

// Namespace namespace_eb31a7ea746bf7d0/namespace_5c22773341178193
// Params 0, eflags: 0x0
// Checksum 0x0, Offset: 0x4ee
// Size: 0x3e0d
function function_29315e279f8c2ec1() {
    while (!(isdefined(level.players[0]) && isdefined(level.players) && isdefined(level.players[0].pers))) {
        waitframe();
    }
    test_begin("player.pers");
    player = level.players[0];
    var_252e3cc32bf76d20 = undefined;
    var_b74dcecaf09f8607 = undefined;
    var_7e7b315fcb2b9159 = undefined;
    arraycopy = undefined;
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Baseline");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_b74dcecaf09f8607 = player.pers["ut_var"];
    var_7e7b315fcb2b9159 = player.pers["ut_struct"];
    arraycopy = player.pers["ut_array"];
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Read non-existent variables");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_252e3cc32bf76d20 = player.pers;
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Make copy of player.pers");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    player.pers["ut_var"] = "a";
    s1 = spawnstruct();
    s1.b = "b";
    s1.c = "c";
    player.pers["ut_struct"] = s1;
    var_ce0ee878f55f5e93 = [];
    var_ce0ee878f55f5e93["d"] = "d";
    var_ce0ee878f55f5e93["e"] = "e";
    player.pers["ut_array"] = var_ce0ee878f55f5e93;
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Add new fields to player.pers");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_252e3cc32bf76d20 = player.pers;
    var_b74dcecaf09f8607 = player.pers["ut_var"];
    var_7e7b315fcb2b9159 = player.pers["ut_struct"];
    arraycopy = player.pers["ut_array"];
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Re-copy everything from player.pers");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_252e3cc32bf76d20["ut_var"] = "aa";
    var_252e3cc32bf76d20["ut_struct"].b = "bb";
    var_252e3cc32bf76d20["ut_struct"].c = "cc";
    var_252e3cc32bf76d20["ut_array"]["d"] = "dd";
    var_252e3cc32bf76d20["ut_array"]["e"] = "ee";
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Update player.pers copy fields");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_b74dcecaf09f8607 = "aaa";
    var_7e7b315fcb2b9159.b = "bbb";
    var_7e7b315fcb2b9159.c = "ccc";
    arraycopy["d"] = "ddd";
    arraycopy["e"] = "eee";
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Update the copies");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    var_252e3cc32bf76d20 = player.pers;
    var_b74dcecaf09f8607 = player.pers["ut_var"];
    var_7e7b315fcb2b9159 = player.pers["ut_struct"];
    arraycopy = player.pers["ut_array"];
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Re-copy everything from player.pers");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    player.pers["ut_var"] = "aaaa";
    player.pers["ut_struct"].b = "bbbb";
    player.pers["ut_struct"].c = "cccc";
    player.pers["ut_array"]["d"] = "dddd";
    player.pers["ut_array"]["e"] = "eeee";
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Update player.pers fields");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    player.pers["ut_var"] = undefined;
    player.pers["ut_struct"] = undefined;
    player.pers["ut_array"] = undefined;
    test_print("-------------------------------------------------------------------------------");
    test_print("" + "Delete player.pers fields");
    test_print("    player.pers.size             - " + (isdefined(player.pers) && isdefined(player.pers.size) ? "" + player.pers.size : "<UNDEFINED>"));
    test_print("    player.pers['ut_var']        - " + (isdefined(player.pers) && isdefined(player.pers["ut_var"]) ? "" + player.pers["ut_var"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].b   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].b) ? "" + player.pers["ut_struct"].b : "<UNDEFINED>"));
    test_print("    player.pers['ut_struct'].c   - " + (isdefined(player.pers["ut_struct"]) && isdefined(player.pers) && isdefined(player.pers["ut_struct"].c) ? "" + player.pers["ut_struct"].c : "<UNDEFINED>"));
    test_print("    player.pers['ut_array'].size - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"].size) ? "" + player.pers["ut_array"].size : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['d'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["d"]) ? "" + player.pers["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    player.pers['ut_array']['e'] - " + (isdefined(player.pers["ut_array"]) && isdefined(player.pers) && isdefined(player.pers["ut_array"]["e"]) ? "" + player.pers["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    persCopy.size                - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20.size) ? "" + var_252e3cc32bf76d20.size : "<UNDEFINED>"));
    test_print("    persCopy['ut_var']           - " + (isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_var"]) ? "" + var_252e3cc32bf76d20["ut_var"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].b      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].b) ? "" + var_252e3cc32bf76d20["ut_struct"].b : "<UNDEFINED>"));
    test_print("    persCopy['ut_struct'].c      - " + (isdefined(var_252e3cc32bf76d20["ut_struct"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_struct"].c) ? "" + var_252e3cc32bf76d20["ut_struct"].c : "<UNDEFINED>"));
    test_print("    persCopy['ut_array'].size    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"].size) ? "" + var_252e3cc32bf76d20["ut_array"].size : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['d']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["d"]) ? "" + var_252e3cc32bf76d20["ut_array"]["d"] : "<UNDEFINED>"));
    test_print("    persCopy['ut_array']['e']    - " + (isdefined(var_252e3cc32bf76d20["ut_array"]) && isdefined(var_252e3cc32bf76d20) && isdefined(var_252e3cc32bf76d20["ut_array"]["e"]) ? "" + var_252e3cc32bf76d20["ut_array"]["e"] : "<UNDEFINED>"));
    test_print("    varCopy                      - " + (isdefined(var_b74dcecaf09f8607) ? "" + var_b74dcecaf09f8607 : "<UNDEFINED>"));
    test_print("    structCopy.b                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.b) ? "" + var_7e7b315fcb2b9159.b : "<UNDEFINED>"));
    test_print("    structCopy.c                 - " + (isdefined(var_7e7b315fcb2b9159) && isdefined(var_7e7b315fcb2b9159.c) ? "" + var_7e7b315fcb2b9159.c : "<UNDEFINED>"));
    test_print("    arrayCopy.size               - " + (isdefined(arraycopy) && isdefined(arraycopy.size) ? "" + arraycopy.size : "<UNDEFINED>"));
    test_print("    arrayCopy['d']               - " + (isdefined(arraycopy) && isdefined(arraycopy["d"]) ? "" + arraycopy["d"] : "<UNDEFINED>"));
    test_print("    arrayCopy['e']               - " + (isdefined(arraycopy) && isdefined(arraycopy["e"]) ? "" + arraycopy["e"] : "<UNDEFINED>"));
    test_end("player.pers");
}

// Namespace namespace_eb31a7ea746bf7d0/namespace_5c22773341178193
// Params 0, eflags: 0x0
// Checksum 0x0, Offset: 0x4302
// Size: 0xa
function main() {
    function_29315e279f8c2ec1();
}

